fixup! python-salttesting: Modify patch to improve ptest output
Patch was not properly regenerated (original author edited the patch
directly) causing build errors:

ERROR: python-salttesting-2016.7.22+gitAUTOINC+095e9020b0-r0 do_patch: Command Error: 'quilt --quiltrc /media/adi/ssd/nilrt-krogoth/build/tmp-glibc/sysroots/x86_64-linux/etc/quiltrc push' exited with 1  Output:
Applying patch 0001-Add-ptest-output-option-to-test-suite.patch
patching file salttesting/parser/__init__.py
Hunk #1 succeeded at 27 (offset 2 lines).
Hunk #2 succeeded at 275 (offset 10 lines).
Hunk #3 succeeded at 525 (offset 27 lines).
patching file salttesting/ptest.py
patch: **** malformed patch at line 227: --

Patch 0001-Add-ptest-output-option-to-test-suite.patch does not apply (enforce with -f)
ERROR: python-salttesting-2016.7.22+gitAUTOINC+095e9020b0-r0 do_patch: Function failed: patch_do_patch

Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>